package com.hr.letters.source;

import com.google.gson.Gson;
import com.hclhrm.util.Util;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.LinkedHashMap;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.json.simple.JSONArray;

@SuppressWarnings({ "resource", "unused", "unchecked", "rawtypes","serial" })
public class EmployeeDetails  extends HttpServlet
{
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
	{
		doPost(request, response);
	}
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
	{
		String relieving = request.getParameter("relieving");
		String routing = request.getParameter("routing");
		String AllDivisions = request.getParameter("AllDivisions");
		JSONArray jsonArray = new JSONArray();

		PrintWriter out = response.getWriter();

		String bu = request.getParameter("Bussinessunit");
		String lettertype = request.getParameter("lettertype");
		String type = request.getParameter("type");
		String employeeid = request.getParameter("employeeid");
		String probation = request.getParameter("probation");
		String date = request.getParameter("date");
		String newctc = request.getParameter("newctc");
		String oldctc = request.getParameter("oldctc");
		String messages = "";


		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try{
			con = Util.getConnection();
		}catch(Exception e){
			e.printStackTrace();
		}
		String qry = "";
		boolean flag = false;
		boolean buflag = false;
		boolean reportflag = false;

		try
		{
			if ((type != null) && (type.equalsIgnoreCase("ViewReport")))
			{
				if ((lettertype.equalsIgnoreCase("AppointmentLetter")) || (lettertype.equalsIgnoreCase("TransferLetter")) || 
						(lettertype.equalsIgnoreCase("PromotionLetter")) || (lettertype.equalsIgnoreCase("ConfirmationLetter")))
				{
					if (employeeid.trim().length() != 0)
					{
						String q = "SELECT EMPLOYEESEQUENCENO FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY WHERE EMPLOYEESEQUENCENO=" + employeeid;
						pstmt = con.prepareStatement(q);
						rs = pstmt.executeQuery();
						if (rs.next())
						{
							flag = true;
							reportflag = true;
						}
						else
						{
							flag = false;
							reportflag = true;
						}
					}
					else if ((!bu.equalsIgnoreCase("Select")) && (employeeid.trim().length() == 0) && (!lettertype.equalsIgnoreCase("Select")))
					{
						if (lettertype.equalsIgnoreCase("AppointmentLetter"))
						{
							qry = 
									"SELECT A.EMPLOYEESEQUENCENO,A.CALLNAME,D.CODE DEPARTMENT,C.CODE DESIGNATION,DATE_FORMAT(E.DATEOFJOIN,'%d-%m-%Y') DOJ FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS B ON A.EMPLOYEEID=B.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION C ON B.DESIGNATIONID=C.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT D ON B.DEPARTMENTID=D.DEPARTMENTID JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE E ON A.EMPLOYEEID=E.EMPLOYEEID WHERE A.COMPANYID IN (" + bu + ") AND B.DESIGNATIONID!=0 AND B.DEPARTMENTID!=0 " + "AND E.DATEOFJOIN!='0000-00-00'";
							buflag = true;
							reportflag = true;
						}
						else if (lettertype.equalsIgnoreCase("TransferLetter"))
						{
							qry = 
									"SELECT A.EMPLOYEESEQUENCENO EMPLOYEEID,A.CALLNAME NAME,IFNULL(DES.CODE,'--') DESIGNATION,DEPT.CODE DEPARTMENT,IFNULL(DATE_FORMAT(PROFILE.DATEOFJOIN,'%d-%m-%Y'),'') DOJ  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID\tLEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN HCLHRM_PROD.TBL_EMPLOYEE_TRANSFERS T ON A.EMPLOYEEID=T.EMPLOYEEID WHERE A.COMPANYID IN (" + bu + ") " + "AND TRANSFERTYPEID=2 AND TRANSFERID=3 AND T.TRANSFERSTATUS='A' AND TRANSFERREDDATE BETWEEN subdate(DATE_FORMAT(NOW(),'%Y-%m-01'), INTERVAL 6 MONTH) AND DATE_FORMAT(NOW(),'%Y-%m-%d') GROUP BY A.EMPLOYEEID";
							buflag = true;
							reportflag = true;
						}
						else if (lettertype.equalsIgnoreCase("PromotionLetter"))
						{
							qry = 
									"SELECT A.EMPLOYEESEQUENCENO EMPLOYEEID,A.CALLNAME NAME,IFNULL(DES.CODE,'--') DESIGNATION,DEPT.CODE DEPARTMENT,IFNULL(DATE_FORMAT(PROFILE.DATEOFJOIN,'%d-%m-%Y'),'') DOJ FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN HCLHRM_PROD.TBL_EMPLOYEE_TRANSFERS T ON A.EMPLOYEEID=T.EMPLOYEEID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS_HISTORY HH ON A.EMPLOYEEID=HH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DD ON HH.DESIGNATIONID=DD.DESIGNATIONID WHERE A.COMPANYID IN (" + bu + ") AND " + "TRANSFERTYPEID=1 AND TRANSFERID=2 AND T.TRANSFERSTATUS='A' AND TRANSFERREDDATE BETWEEN subdate(DATE_FORMAT(NOW(),'%Y-%m-01'), INTERVAL 6 MONTH) AND DATE_FORMAT(NOW(),'%Y-%m-%d') GROUP BY A.EMPLOYEEID";
							buflag = true;
							reportflag = true;
						}
						else if (lettertype.equalsIgnoreCase("ConfirmationLetter"))
						{
							qry = 
									"SELECT A.EMPLOYEESEQUENCENO EMPLOYEEID,A.CALLNAME NAME,IFNULL(DES.CODE,'--') DESIGNATION,DEPT.CODE DEPARTMENT,IFNULL(DATE_FORMAT(PROFILE.DATEOFJOIN,'%d-%m-%Y'),'') DOJ FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN TEST.TBL_EMPLOYEE_CONFIRMATION_DETAILS TEST ON A.EMPLOYEEID=TEST.EMPLOYEEID WHERE A.COMPANYID IN (" + bu + ") GROUP BY A.EMPLOYEEID HAVING MAX(TEST.LUPDATE)";
							buflag = true;
							reportflag = true;
						}
					}
					else if ((bu.equalsIgnoreCase("Select")) && (employeeid.trim().length() == 0) && (!lettertype.equalsIgnoreCase("Select")))
					{
						if (lettertype.equalsIgnoreCase("ConfirmationLetter"))
						{
							qry = 
									"SELECT A.EMPLOYEESEQUENCENO EMPLOYEEID,A.CALLNAME NAME,IFNULL(DES.CODE,'--') DESIGNATION,DEPT.CODE DEPARTMENT,IFNULL(DATE_FORMAT(PROFILE.DATEOFJOIN,'%d-%m-%Y'),'') DOJ FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN TEST.TBL_EMPLOYEE_CONFIRMATION_DETAILS TEST ON A.EMPLOYEEID=TEST.EMPLOYEEID WHERE A.COMPANYID IN (" + AllDivisions + ")" + " GROUP BY A.EMPLOYEEID HAVING MAX(TEST.LUPDATE)";
							buflag = true;
							reportflag = true;
						} else if (lettertype.equalsIgnoreCase("PromotionLetter"))
						{
							qry = 
									"SELECT A.EMPLOYEESEQUENCENO EMPLOYEEID,A.CALLNAME NAME,IFNULL(DES.CODE,'--') DESIGNATION,DEPT.CODE DEPARTMENT,IFNULL(DATE_FORMAT(PROFILE.DATEOFJOIN,'%d-%m-%Y'),'') DOJ FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN HCLHRM_PROD.TBL_EMPLOYEE_TRANSFERS T ON A.EMPLOYEEID=T.EMPLOYEEID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS_HISTORY HH ON A.EMPLOYEEID=HH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DD ON HH.DESIGNATIONID=DD.DESIGNATIONID WHERE TRANSFERTYPEID=1 AND TRANSFERID=2 AND T.TRANSFERSTATUS='A' AND A.COMPANYID IN (" + AllDivisions + ") AND " + "TRANSFERREDDATE BETWEEN subdate(DATE_FORMAT(NOW(),'%Y-%m-01'), INTERVAL 6 MONTH) AND DATE_FORMAT(NOW(),'%Y-%m-%d') GROUP BY A.EMPLOYEEID";
							buflag = true;
							reportflag = true;
						} else if (lettertype.equalsIgnoreCase("TransferLetter"))
						{
							qry = 
									"SELECT A.EMPLOYEESEQUENCENO EMPLOYEEID,A.CALLNAME NAME,IFNULL(DES.CODE,'--') DESIGNATION,DEPT.CODE DEPARTMENT,IFNULL(DATE_FORMAT(PROFILE.DATEOFJOIN,'%d-%m-%Y'),'') DOJ  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID\tLEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN HCLHRM_PROD.TBL_EMPLOYEE_TRANSFERS T ON A.EMPLOYEEID=T.EMPLOYEEID WHERE TRANSFERTYPEID=2 AND TRANSFERID=3 AND T.TRANSFERSTATUS='A' AND A.COMPANYID IN (" + AllDivisions + ") " + "AND TRANSFERREDDATE BETWEEN subdate(DATE_FORMAT(NOW(),'%Y-%m-01'), INTERVAL 6 MONTH) AND DATE_FORMAT(NOW(),'%Y-%m-%d') GROUP BY A.EMPLOYEEID";
							buflag = true;
							reportflag = true;
						}
						else if (lettertype.equalsIgnoreCase("AppointmentLetter"))
						{
							qry = 
									"SELECT A.EMPLOYEESEQUENCENO,A.CALLNAME,D.CODE DEPARTMENT,C.CODE DESIGNATION,DATE_FORMAT(E.DATEOFJOIN,'%d-%m-%Y') DOJ  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS B ON A.EMPLOYEEID=B.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION C ON B.DESIGNATIONID=C.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT D ON B.DEPARTMENTID=D.DEPARTMENTID JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE E ON A.EMPLOYEEID=E.EMPLOYEEID WHERE A.COMPANYID IN (" + AllDivisions + ") AND B.DESIGNATIONID!=0 AND B.DEPARTMENTID!=0 " + "AND E.DATEOFJOIN!='0000-00-00'";
							buflag = true;
							reportflag = true;
						}
					}
				}
			}


			String countqry = "";


			if ((routing != null) && (routing.equalsIgnoreCase("ReGenerate")) && (type.equalsIgnoreCase("ViewReport")))
			{
				if ((flag) && (lettertype.equalsIgnoreCase("AppointmentLetter")) && (!bu.equalsIgnoreCase("Select")))
				{
					countqry = 
							"SELECT A.EMPLOYEESEQUENCENO  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS B ON A.EMPLOYEEID=B.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION C ON B.DESIGNATIONID=C.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT D ON B.DEPARTMENTID=D.DEPARTMENTID JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE E ON A.EMPLOYEEID=E.EMPLOYEEID WHERE A.COMPANYID IN (" + bu + ") AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND B.DESIGNATIONID!=0 AND B.DEPARTMENTID!=0 " + "AND E.DATEOFJOIN!='0000-00-00'";
					pstmt = con.prepareStatement(countqry);
					rs = pstmt.executeQuery();
					if (rs.next())
					{
						reportflag = true;
					}
					else
					{
						reportflag = false;
					}

					if (reportflag)
					{
						qry = 
								"SELECT A.EMPLOYEESEQUENCENO,A.CALLNAME,D.CODE DEPARTMENT,C.CODE DESIGNATION,DATE_FORMAT(E.DATEOFJOIN,'%d-%m-%Y') DOJ FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS B ON A.EMPLOYEEID=B.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION C ON B.DESIGNATIONID=C.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT D ON B.DEPARTMENTID=D.DEPARTMENTID JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE E ON A.EMPLOYEEID=E.EMPLOYEEID WHERE A.COMPANYID IN (" + bu + ") AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND B.DESIGNATIONID!=0 AND B.DEPARTMENTID!=0 " + "AND E.DATEOFJOIN!='0000-00-00'";
						flag = true;
					}
				}
				else if ((flag) && (lettertype.equalsIgnoreCase("AppointmentLetter")) && (bu.equalsIgnoreCase("Select")))
				{
					countqry = 
							"SELECT A.EMPLOYEESEQUENCENO FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS B ON A.EMPLOYEEID=B.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION C ON B.DESIGNATIONID=C.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT D ON B.DEPARTMENTID=D.DEPARTMENTID JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE E ON A.EMPLOYEEID=E.EMPLOYEEID WHERE A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND A.COMPANYID IN (" + AllDivisions + ")  AND B.DESIGNATIONID!=0 AND B.DEPARTMENTID!=0 " + "AND E.DATEOFJOIN!='0000-00-00'";
					pstmt = con.prepareStatement(countqry);
					rs = pstmt.executeQuery();
					if (rs.next())
					{
						reportflag = true;
					}
					else
					{
						reportflag = false;
					}

					if (reportflag)
					{
						qry = 
								"SELECT A.EMPLOYEESEQUENCENO,A.CALLNAME,D.CODE DEPARTMENT,C.CODE DESIGNATION,DATE_FORMAT(E.DATEOFJOIN,'%d-%m-%Y') DOJ FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS B ON A.EMPLOYEEID=B.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION C ON B.DESIGNATIONID=C.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT D ON B.DEPARTMENTID=D.DEPARTMENTID JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE E ON A.EMPLOYEEID=E.EMPLOYEEID WHERE A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND A.COMPANYID IN (" + AllDivisions + ") AND B.DESIGNATIONID!=0 AND B.DEPARTMENTID!=0 " + "AND E.DATEOFJOIN!='0000-00-00'";
						String insert = "INSERT INTO test.appointmentletter_history  (SNO, EMPLOYEEID, PROBATION, RELIEVING,OFFERDATE, STATUS) SELECT SNO, EMPLOYEEID, PROBATION, RELIEVING,OFFERDATE, STATUS FROM test.appointmentletter WHERE EMPLOYEEID='" + 
								employeeid + "'";
						pstmt = con.prepareStatement(insert);
						int b = pstmt.executeUpdate();
						String update = "UPDATE test.appointmentletter SET PROBATION='" + probation + "',RELIEVING='" + relieving + "',OFFERDATE=DATE_FORMAT(STR_TO_DATE('" + date + "', '%d-%m-%Y'), '%Y-%m-%d') WHERE EMPLOYEEID='" + employeeid + "'";
						pstmt = con.prepareStatement(update);
						int c = pstmt.executeUpdate();
						flag = true;
					}
				}
			}
			if ((flag) && (lettertype.equalsIgnoreCase("TransferLetter")) && (!bu.equalsIgnoreCase("Select")))
			{
				countqry = 
						"SELECT A.EMPLOYEESEQUENCENO  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID JOIN HCLHRM_PROD.TBL_EMPLOYEE_TRANSFERS T ON A.EMPLOYEEID=T.EMPLOYEEID WHERE TRANSFERTYPEID=2 AND TRANSFERID=3 AND T.TRANSFERSTATUS='A' AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND A.COMPANYID IN (" + bu + ") AND " + "TRANSFERREDDATE BETWEEN subdate(DATE_FORMAT(NOW(),'%Y-%m-01'), INTERVAL 6 MONTH) AND DATE_FORMAT(NOW(),'%Y-%m-%d') GROUP BY A.EMPLOYEEID";
				pstmt = con.prepareStatement(countqry);
				rs = pstmt.executeQuery();
				if (rs.next())
				{
					reportflag = true;
				}
				else
				{
					reportflag = false;
				}
				if (reportflag)
				{
					qry = 
							"SELECT A.EMPLOYEESEQUENCENO ID,A.CALLNAME,IFNULL(DES.CODE,'--') DESIGNATION,DEPT.CODE DEPARTMENT,IFNULL(PROFILE.DATEOFJOIN,'') DOJ  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID\tLEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN HCLHRM_PROD.TBL_EMPLOYEE_TRANSFERS T ON A.EMPLOYEEID=T.EMPLOYEEID WHERE T.TRANSFERTYPEID=2 AND T.TRANSFERID=3 AND T.TRANSFERSTATUS='A' AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND A.COMPANYID IN (" + bu + ") AND " + "TRANSFERREDDATE BETWEEN subdate(DATE_FORMAT(NOW(),'%Y-%m-01'), INTERVAL 6 MONTH) AND DATE_FORMAT(NOW(),'%Y-%m-%d') GROUP BY A.EMPLOYEEID";
					flag = true;
				}
			}
			else if ((flag) && (lettertype.equalsIgnoreCase("TransferLetter")) && (bu.equalsIgnoreCase("Select")))
			{
				countqry = 
						"SELECT A.EMPLOYEESEQUENCENO  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID JOIN HCLHRM_PROD.TBL_EMPLOYEE_TRANSFERS T ON A.EMPLOYEEID=T.EMPLOYEEID WHERE TRANSFERTYPEID=2 AND TRANSFERID=3 AND T.TRANSFERSTATUS='A' AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND TRANSFERREDDATE BETWEEN subdate(DATE_FORMAT(NOW(),'%Y-%m-01'), INTERVAL 6 MONTH) AND DATE_FORMAT(NOW(),'%Y-%m-%d') GROUP BY A.EMPLOYEEID";
				pstmt = con.prepareStatement(countqry);
				rs = pstmt.executeQuery();
				if (rs.next())
				{
					reportflag = true;

				}
				else
				{
					reportflag = false;
				}

				if (reportflag)
				{


					qry ="SELECT A.EMPLOYEESEQUENCENO ID,A.CALLNAME,IFNULL(DES.CODE,'--') DESIGNATION,DEPT.CODE DEPARTMENT,IFNULL(PROFILE.DATEOFJOIN,'') DOJ  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID\tLEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN HCLHRM_PROD.TBL_EMPLOYEE_TRANSFERS T ON A.EMPLOYEEID=T.EMPLOYEEID WHERE TRANSFERTYPEID=2 AND TRANSFERID=3 AND T.TRANSFERSTATUS='A' AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND " + "TRANSFERREDDATE BETWEEN subdate(DATE_FORMAT(NOW(),'%Y-%m-01'), INTERVAL 6 MONTH) AND DATE_FORMAT(NOW(),'%Y-%m-%d') GROUP BY A.EMPLOYEEID";
					flag = true;
				}
			}


			if ((flag) && (lettertype.equalsIgnoreCase("PromotionLetter")) && (!bu.equalsIgnoreCase("Select")))
			{

				countqry ="SELECT A.EMPLOYEESEQUENCENO  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID JOIN HCLHRM_PROD.TBL_EMPLOYEE_TRANSFERS T ON A.EMPLOYEEID=T.EMPLOYEEID WHERE TRANSFERTYPEID=1 AND TRANSFERID=2 AND T.TRANSFERSTATUS='A' AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND A.COMPANYID IN (" + bu + ") " + "GROUP BY A.EMPLOYEEID";

				pstmt = con.prepareStatement(countqry);
				rs = pstmt.executeQuery();
				if (rs.next())
				{
					reportflag = true;

				}
				else
				{
					reportflag = false;
				}

				if (reportflag)
				{
					qry ="SELECT A.EMPLOYEESEQUENCENO ID,A.CALLNAME,IFNULL(DES.CODE,'--') DESIGNATION,DEPT.CODE DEPARTMENT,IFNULL(PROFILE.DATEOFJOIN,'') DOJ  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID\tLEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN HCLHRM_PROD.TBL_EMPLOYEE_TRANSFERS T ON A.EMPLOYEEID=T.EMPLOYEEID WHERE TRANSFERTYPEID=1 AND TRANSFERID=2 AND T.TRANSFERSTATUS='A' AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND A.COMPANYID IN (" + bu + ") " + " GROUP BY A.EMPLOYEEID";



					String promotioncheck = " SELECT IF(B.employeeid=A.employeeid, '1', '0') as history FROM test.promotionletter A LEFT JOIN test.promotionletter_history B ON  A.EMPLOYEEID=B.EMPLOYEEID where A.EMPLOYEEID='" + 
							employeeid + "'";

					pstmt = con.prepareStatement(promotioncheck);
					rs = pstmt.executeQuery();
					int History = 0;
					if (rs.next())
					{
						History = rs.getInt(1);
					}
					if ((History == 0) || (History == 1))
					{

						String HistoryInsert = "INSERT INTO test.promotionletter_history (SNO,EMPLOYEEID, OLDCTC, NEWCTC, DATE,STATUS) SELECT  SNO,EMPLOYEEID,OLDCTC,NEWCTC,DATE,STATUS FROM test.promotionletter WHERE employeeid='" + 
								employeeid + "'";


						pstmt = con.prepareStatement(HistoryInsert);
						pstmt.executeUpdate();
					}

					String Update = "UPDATE test.promotionletter SET OLDCTC='" + oldctc + "',NEWCTC='" + newctc + "' WHERE EMPLOYEEID='" + employeeid + "'";

					pstmt = con.prepareStatement(Update);
					int b = pstmt.executeUpdate();
					flag = true;
				}
			}
			else if ((flag) && (lettertype.equalsIgnoreCase("PromotionLetter")) && (bu.equalsIgnoreCase("Select")))
			{

				countqry ="SELECT A.EMPLOYEESEQUENCENO  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID JOIN HCLHRM_PROD.TBL_EMPLOYEE_TRANSFERS T ON A.EMPLOYEEID=T.EMPLOYEEID WHERE TRANSFERTYPEID=1 AND TRANSFERID=2 AND T.TRANSFERSTATUS='A' AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND A.COMPANYID IN (" + AllDivisions + ") GROUP BY A.EMPLOYEEID";

				pstmt = con.prepareStatement(countqry);
				rs = pstmt.executeQuery();
				if (rs.next())
				{
					reportflag = true;

				}
				else
				{
					reportflag = false;
				}

				if (reportflag)
				{
					qry ="SELECT A.EMPLOYEESEQUENCENO ID,A.CALLNAME,IFNULL(DES.CODE,'--') DESIGNATION,DEPT.CODE DEPARTMENT,IFNULL(PROFILE.DATEOFJOIN,'') DOJ  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID\tLEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN HCLHRM_PROD.TBL_EMPLOYEE_TRANSFERS T ON A.EMPLOYEEID=T.EMPLOYEEID WHERE TRANSFERTYPEID=1 AND TRANSFERID=2 AND T.TRANSFERSTATUS='A' AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND A.COMPANYID IN (" + AllDivisions + ") GROUP BY A.EMPLOYEEID";



					String promotioncheck = " SELECT IF(B.employeeid=A.employeeid, '1', '0') as history FROM test.promotionletter A LEFT JOIN test.promotionletter_history B ON  A.EMPLOYEEID=B.EMPLOYEEID where A.EMPLOYEEID='" + 
							employeeid + "'";

					pstmt = con.prepareStatement(promotioncheck);
					rs = pstmt.executeQuery();
					int History = 0;
					if (rs.next())
					{
						History = rs.getInt(1);
					}
					if ((History == 0) || (History == 1))
					{

						String HistoryInsert = "INSERT INTO test.promotionletter_history (EMPLOYEEID, OLDCTC, NEWCTC, DATE,STATUS) SELECT  EMPLOYEEID,OLDCTC,NEWCTC,DATE,STATUS FROM test.promotionletter WHERE employeeid='" + 
								employeeid + "'";


						pstmt = con.prepareStatement(HistoryInsert);
						pstmt.executeUpdate();
					}

					String Update = "INSERT INTO test.promotionletter (EMPLOYEEID,OLDCTC,NEWCTC,DATE) VALUES ('" + employeeid + "','" + oldctc + "','" + newctc + "',DATE_FORMAT(NOW(),'%Y-%m-%d')) " + 
							" ON DUPLICATE KEY UPDATE OLDCTC='" + oldctc + "',NEWCTC='" + newctc + "',EMPLOYEEID='" + employeeid + "',DATE=DATE_FORMAT(NOW(),'%Y-%m-%d')";

					pstmt = con.prepareStatement(Update);
					int b = pstmt.executeUpdate();


					flag = true;
				}
			}

			if ((flag) && (lettertype.equalsIgnoreCase("ConfirmationLetter")) && (!bu.equalsIgnoreCase("Select")))
			{

				countqry = " SELECT A.EMPLOYEESEQUENCENO FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN TEST.TBL_EMPLOYEE_CONFIRMATION_DETAILS TEST ON A.EMPLOYEEID=TEST.EMPLOYEEID WHERE A.COMPANYID IN (" + bu + ") AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") GROUP BY A.EMPLOYEEID HAVING MAX(TEST.LUPDATE)";
				pstmt = con.prepareStatement(countqry);
				rs = pstmt.executeQuery();
				if (rs.next())
				{
					reportflag = true;

				}
				else
				{
					reportflag = false;
				}

				if (reportflag)
				{
					qry = 

							"SELECT A.EMPLOYEESEQUENCENO EMPLOYEEID,A.CALLNAME NAME,IFNULL(DES.CODE,'--') DESIGNATION,DEPT.CODE DEPARTMENT,IFNULL(DATE_FORMAT(PROFILE.DATEOFJOIN,'%d-%m-%Y'),'') DOJ FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN TEST.TBL_EMPLOYEE_CONFIRMATION_DETAILS TEST ON A.EMPLOYEEID=TEST.EMPLOYEEID WHERE A.COMPANYID IN (" + bu + ") AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") GROUP BY A.EMPLOYEEID HAVING MAX(TEST.LUPDATE)";


					flag = true;

				}



			}
			else if ((flag) && (lettertype.equalsIgnoreCase("ConfirmationLetter")) && (bu.equalsIgnoreCase("Select")))
			{

				countqry = 

						" SELECT A.EMPLOYEESEQUENCENO FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN TEST.TBL_EMPLOYEE_CONFIRMATION_DETAILS TEST ON A.EMPLOYEEID=TEST.EMPLOYEEID WHERE A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND A.COMPANYID IN (" + AllDivisions + ") GROUP BY A.EMPLOYEEID HAVING MAX(TEST.LUPDATE)";
				pstmt = con.prepareStatement(countqry);
				rs = pstmt.executeQuery();
				if (rs.next())
				{
					reportflag = true;

				}
				else
				{
					reportflag = false;
				}

				if (reportflag)
				{

					qry = 
							"SELECT A.EMPLOYEESEQUENCENO EMPLOYEEID,A.CALLNAME NAME,IFNULL(DES.CODE,'--') DESIGNATION,DEPT.CODE DEPARTMENT,IFNULL(DATE_FORMAT(PROFILE.DATEOFJOIN,'%d-%m-%Y'),'') DOJ FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT BU ON A.COMPANYID=BU.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY_HISTORY PH ON A.EMPLOYEEID=PH.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_BUSINESSUNIT HB ON PH.COMPANYID=HB.BUSINESSUNITID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS PRO ON A.EMPLOYEEID=PRO.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION DES ON PRO.DESIGNATIONID=DES.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT DEPT ON PRO.DEPARTMENTID=DEPT.DEPARTMENTID LEFT JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE PROFILE ON A.EMPLOYEEID=PROFILE.EMPLOYEEID JOIN TEST.TBL_EMPLOYEE_CONFIRMATION_DETAILS TEST ON A.EMPLOYEEID=TEST.EMPLOYEEID WHERE A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND A.COMPANYID IN (" + AllDivisions + ") GROUP BY A.EMPLOYEEID HAVING MAX(TEST.LUPDATE)";


					flag = true;
				}
			}

			if ((flag) && (lettertype.equalsIgnoreCase("AppointmentLetter")) && (!bu.equalsIgnoreCase("Select")))
			{


				countqry = 

						"SELECT A.EMPLOYEESEQUENCENO  FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS B ON A.EMPLOYEEID=B.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION C ON B.DESIGNATIONID=C.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT D ON B.DEPARTMENTID=D.DEPARTMENTID JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE E ON A.EMPLOYEEID=E.EMPLOYEEID WHERE A.COMPANYID IN (" + bu + ") AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND B.DESIGNATIONID!=0 AND B.DEPARTMENTID!=0 " + "AND E.DATEOFJOIN!='0000-00-00'";

				pstmt = con.prepareStatement(countqry);
				rs = pstmt.executeQuery();
				if (rs.next())
				{
					reportflag = true;

				}
				else
				{
					reportflag = false;
				}

				if (reportflag)
				{

					qry = 

							"SELECT A.EMPLOYEESEQUENCENO,A.CALLNAME,D.CODE DEPARTMENT,C.CODE DESIGNATION,DATE_FORMAT(E.DATEOFJOIN,'%d-%m-%Y') DOJ FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS B ON A.EMPLOYEEID=B.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION C ON B.DESIGNATIONID=C.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT D ON B.DEPARTMENTID=D.DEPARTMENTID JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE E ON A.EMPLOYEEID=E.EMPLOYEEID WHERE A.COMPANYID IN (" + bu + ") AND A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND B.DESIGNATIONID!=0 AND B.DEPARTMENTID!=0 " + "AND E.DATEOFJOIN!='0000-00-00'";


					flag = true;
				}
			}
			else if ((flag) && (lettertype.equalsIgnoreCase("AppointmentLetter")) && (bu.equalsIgnoreCase("Select")))
			{


				countqry = 

						"SELECT A.EMPLOYEESEQUENCENO FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS B ON A.EMPLOYEEID=B.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION C ON B.DESIGNATIONID=C.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT D ON B.DEPARTMENTID=D.DEPARTMENTID JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE E ON A.EMPLOYEEID=E.EMPLOYEEID WHERE A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND A.COMPANYID IN (" + AllDivisions + ")  AND B.DESIGNATIONID!=0 AND B.DEPARTMENTID!=0 " + "AND E.DATEOFJOIN!='0000-00-00'";
				pstmt = con.prepareStatement(countqry);
				rs = pstmt.executeQuery();
				if (rs.next())
				{
					reportflag = true;

				}
				else
				{
					reportflag = false;
				}

				if (reportflag)
				{


					qry = 

							"SELECT A.EMPLOYEESEQUENCENO,A.CALLNAME,D.CODE DEPARTMENT,C.CODE DESIGNATION,DATE_FORMAT(E.DATEOFJOIN,'%d-%m-%Y') DOJ FROM HCLHRM_PROD.TBL_EMPLOYEE_PRIMARY A JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFESSIONAL_DETAILS B ON A.EMPLOYEEID=B.EMPLOYEEID LEFT JOIN HCLADM_PROD.TBL_DESIGNATION C ON B.DESIGNATIONID=C.DESIGNATIONID LEFT JOIN HCLADM_PROD.TBL_DEPARTMENT D ON B.DEPARTMENTID=D.DEPARTMENTID JOIN HCLHRM_PROD.TBL_EMPLOYEE_PROFILE E ON A.EMPLOYEEID=E.EMPLOYEEID WHERE A.EMPLOYEESEQUENCENO IN (" + employeeid + ") AND A.COMPANYID IN (" + AllDivisions + ") AND B.DESIGNATIONID!=0 AND B.DEPARTMENTID!=0 " + "AND E.DATEOFJOIN!='0000-00-00'";

					String appointmentcheck = " SELECT IF(B.employeeid=A.employeeid, '1', '0') as history FROM test.appointmentletter A LEFT JOIN test.appointmentletter_history B ON  A.EMPLOYEEID=B.EMPLOYEEID where A.EMPLOYEEID='" + 
							employeeid + "'";
					pstmt = con.prepareStatement(appointmentcheck);
					rs = pstmt.executeQuery();
					int History = 0;
					if (rs.next())
					{
						History = rs.getInt(1);
					}
					if ((History == 0) || (History == 1))
					{

						String HistoryInsert = "INSERT INTO test.appointmentletter_history (EMPLOYEEID,PROBATION,RELIEVING,OFFERDATE,STATUS) SELECT  EMPLOYEEID,PROBATION,RELIEVING,DATE_FORMAT(OFFERDATE,'%Y-%m-%d'),STATUS FROM test.appointmentletter WHERE employeeid='" + 
								employeeid + "'";


						pstmt = con.prepareStatement(HistoryInsert);
						pstmt.executeUpdate();
					}

					String Update = "INSERT INTO test.appointmentletter (EMPLOYEEID,PROBATION,RELIEVING,OFFERDATE) VALUES ('" + employeeid + "','" + probation + "','" + relieving + "',DATE_FORMAT(STR_TO_DATE('" + date + "', '%d-%m-%Y'), '%Y-%m-%d')) " + 
							" ON DUPLICATE KEY UPDATE PROBATION='" + probation + "',RELIEVING='" + relieving + "',EMPLOYEEID='" + employeeid + "',OFFERDATE=DATE_FORMAT(STR_TO_DATE('" + date + "', '%d-%m-%Y'), '%Y-%m-%d')";

					System.out
					.println("3");
					pstmt = con.prepareStatement(Update);
					int c = pstmt.executeUpdate();


					flag = true;
				}
			}





			if (reportflag)
			{



				if ((flag) || (buflag))
				{


					pstmt = con.prepareStatement(qry);
					rs = pstmt.executeQuery();
					ResultSetMetaData metadata = rs.getMetaData();
					int columnCount = metadata.getColumnCount();
					LinkedHashMap hm = new LinkedHashMap();


					while (rs.next())
					{
						hm = new LinkedHashMap();


						for (int i = 1; i <= columnCount; i++)
						{



							hm.put("#<input type='checkbox' value='CheckAll' id='CheckAll' onclick='CheckAllData(this);'>", "<input type='checkbox' name='check'  value=" + rs.getString(1) + " onclick='Check(this)' id=" + rs.getString(1) + ">");

							hm.put(metadata.getColumnLabel(i), rs.getString(i));
						}

						hm.put("Print", "<input type='button' value='print' name='employeeid'  id=" + rs.getString(1) + " onclick='Print(this);'>");
						jsonArray.add(hm);
					}


					Gson gson = new Gson();
					messages = gson.toJson(jsonArray);


				}
				else
				{


					messages = "1";

				}



			}
			else
			{
				messages = "2";
			}

			out.println(messages);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
	}
}
